# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe-bundler", ">=1.1", :group => [:development, :test]
gem "hoe-gemspec", ">=1.0", :group => [:development, :test]
gem "rake", ">=0.9", :group => [:development, :test]
gem "rake-compiler", "=0.8.0", :group => [:development, :test]
gem "git", ">=0", :group => [:development, :test]
gem "rspec", ">=0", :group => [:development, :test]
gem "hoe", "~>3.1", :group => [:development, :test]

# vim: syntax=ruby
